server:
  port: 0

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:tcp://localhost/~/cloud
    username: cjswo
    password: duddn
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

greeting:
  message: welcome E-commerce

#token:
#  expiration_time: 864000
#  shared_key: cjswoduddnwkftodrlsduddnszkzkdhdpdlqtktgkfduddnchqhd6cjsWlrdmfduddn

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans
